name: my_plant
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  camera: ^0.11.0
  image: ^3.0.1 # 최신 버전으로 수정
  socket_io_client: ^1.0.2
  permission_handler: ^11.1.0
  audioplayers: ^6.0.0
  file_picker: ^5.2.3
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  tflite_flutter: ^0.9.0
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/back.png
    - assets/plant_model.tflite
    - assets/plant_labels.txt
    - assets/clover_model.tflite
    - assets/clover_labels.txt
    - assets/청옥.JPG
    - assets/장미허브.JPG
    - assets/라울.JPG
    - assets/괴마옥.JPG
    - assets/레티지아.JPG
    - assets/모닐리포메.JPG
    - assets/미니염자.JPG
    - assets/축전.JPG
    - assets/1.m4a
